# global debug
debug: false
# for actuator
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.spring.projectboard: debug
    org.springframework.web.servlet: debug # response, request debug 를 위한 설정
    org.hibernate.type.descriptor.sql.BasicBinder: trace # jpa 사용시 query debug 를 위한 설정

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: joo
    password: thisisTestpw!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true # test에 사용될 *.sql을 사용할 수 있게 함
    hibernate.ddl-auto: create # 자동으로 DDL문을 작성하여 table을 생성
    show-sql: true
    properties:
      hibernate.format_sql: true # formatting
      hibernate.default_batch_fetch_size: 100 #
  h2.console.enabled: false # default=false
  sql.init.mode: always
  data.rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true

---

spring:
  config.activate.on-profile: ${PROFILE}
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  hibernate.ddl-auto: create
  sql.init.mode: always
