# global debug
debug: false
# for actuator
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.spring.projectboard: debug
    org.springframework.web.servlet: debug # response, request debug 를 위한 설정
    org.hibernate.type.descriptor.sql.BasicBinder: trace # jpa 사용시 query debug 를 위한 설정

spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    open-in-view: false
    defer-datasource-initialization: true # test에 사용될 *.sql을 사용할 수 있게 함
    hibernate.ddl-auto: create # 자동으로 DDL문을 작성하여 table을 생성
    show-sql: true
    properties:
      hibernate.format_sql: true # formatting
      hibernate.default_batch_fetch_size: 100 #
  h2.console.enabled: false # default=false
  sql.init.mode: always
  data.rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3.decoupled-logic: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            # REST API 키
            client-id: ${KAKAO_OAUTH_CLIENT_ID}
            # 보안 > Client Secret 코드
            client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: POST
        provider:
          kakao:
            # https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#request-code
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            # https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#request-token
            token-uri: https://kauth.kakao.com/oauth/token
            # https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#req-user-info
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

---

spring:
  config.activate.on-profile: test
  datasource.url: jdbc:h2:mem:testdb